
name: Run API

on:
  workflow_dispatch:

env:
    API_KEY: ${{secrets.TMDB_API_KEY}}
  

jobs:

  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code

        uses: actions/checkout@v4

      - name: Setup Python

        uses: actions/setup-python@v4

        with:

          python-version: '3.11'

      # Runs a set of commands using the runners shell
      - name: Run Python script
        run: |
          pip install requests
          python recomendationModelAPI/movies.py
        
